[project]
name = "extractstructdata"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Leni Đuderija", email = "leni.duderija@q.agency" }
]
requires-python = ">=3.13"
dependencies = [
    "anthropic>=1.2.0",
    "jsonschema>=4.26.0",
    "pypdf>=6.16.2",
    "python-dotenv>=1.2.3",
    "requests>=2.34.2",
    "trafilatura>=2.2.0",
]

[project.scripts]
extractstructdata = "extractstructdata:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
